apiVersion: v1
kind: Service
metadata:
  name: bedrock-api-bridge
  labels:
    app: bedrock-api-bridge
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: bedrock-api-bridge