name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov flake8
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        pip install -r requirements.txt
    
    - name: Run linter
      run: |
        flake8 app tests --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Run tests
      run: |
        pytest --cov=app tests/
        
  build:
    name: Build Docker Image
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: bedrock-api-bridge:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        # Adding load: true would make the image available for extra testing steps
        # load: true
    
    # Optional: Run additional tests on the built image
    # - name: Test Docker image
    #   run: |
    #     docker run --rm bedrock-api-bridge:latest python -m pytest /app/tests
    
    # You can add an optional step to publish the image to a registry
    # for manual deployment if needed (but without CD automation)
    # This would require setting up registry authentication
    
    - name: Summary
      run: |
        echo "✅ CI Process Completed Successfully"
        echo "✅ Tests passed"
        echo "✅ Docker image built successfully"
        echo ""
        echo "The image can now be manually deployed by your operations team."